### ISSUE TITLE
how nerve-etcd can register/health check a service backend container which is started after nerve-etcd 

### ISSUE THREAD

**Issue by YanXiaoping** [bobtfish/nerve-etcd#1]
As stated in Readme, nerve-etcd can be used in such way:
docker run -d you/testservice --expose 8080 --name testservice1
docker run -d -e NERVE_SERVICE=testservice --link etcd:etcd --link testservice1:testservice1 --name testservice-registration bobtfish/nerve-etcd

If after some time, I want to run a new container instance of testservice.
What should I do to let nerve-etcd to health check and register this new instance of test service?

Thank you.

**Comment by bobtfish** [comment]
You need to run this as a sidecar - i.e. 1 instance of nerve per container instance of the service. So the basic answer is just to start another one :)

**Comment by YanXiaoping** [comment]
Ok, but isn't it better to run single nerve instance per host?

**Comment by bobtfish** [comment]
Yes. This container is mostly meant for do demo purposes (which is why it
also only supports TCP health checks)

**Comment by YanXiaoping** [comment]
Ok, is there planned/ongoing project in nerve community to fully support containerized application (I mean not only for demo)?

**Comment by bobtfish** [comment]
Not AFAIK as that solution likely wouldn't be very generic.

Airbnb aren't really maintaining Nerve any more, and whilst we at Yelp are,
we run it direct on hosts. We have however just open sourced all our tools
and wrappers in paasta (our PAAS)
